#Example usage:
# export COLLECTION_ID=9200396
# export METADATA_PATH="${HOME}/Documents/Projects/Europeana/fulltext/dumps/edm-md/${COLLECTION_ID}"
# export FULLTEXT_PATH="${HOME}/Documents/Projects/Europeana/fulltext/dumps/edm-issue/${COLLECTION_ID}"
# export BASE_URL="https://www.clarin.eu/resources/europeana/fulltext/${COLLECTION_ID}/"
# export OUTPUT_DIR="$(pwd)/output"
# docker-compose run europeana-aggregator process



version: "3.3"
services:
  europeana-aggregator:
    image: europeana-aggregator:latest
    build: ./image
    environment:
      - METADATA_PATH=/input/metadata
      - FULLTEXT_PATH=/input/fulltext
      - OUTPUT_DIR=/output
      - IIIF_API_URL=https://iiif.europeana.eu
      - API_RETRIEVAL_THREAD_POOL_SIZE=10
    volumes:
      - "${LOCAL_OUTPUT_DIR:-./output}:/output"
      - input-storage:/input
volumes:
  input-storage:
