version: "3.9"
services:
  europeana-aggregator:
    image: europeana-aggregator:latest
    build: ./image
    environment:
      - SEARCH_API_URL
      - SEARCH_API_KEY
      - IIIF_API_URL
      - RECORD_RETRIEVAL_LIMIT
      - OUTPUT_DIR=/output
    volumes:
      - "${OUTPUT_DIR}:/output"
