version: "3.3"
services:
  europeana-aggregator:
    image: europeana-aggregator:latest
    build: ./image
    environment:
      - RECORD_API_KEY=${RECORD_API_KEY:?Europeana API key must be set}
      - CMDI_RECORDS_BASE_URL=${CMDI_RECORDS_BASE_URL:?Records base URL be set}
      - METADATA_PATH=/input/metadata
      - FULLTEXT_PATH=/input/fulltext
      - OUTPUT_DIR=/output
      - IIIF_API_URL=https://iiif.europeana.eu
      - RECORD_API_URL=https://api.europeana.eu/record/v2
      - LANDING_PAGE_URL=https://pro.europeana.eu/page/iiif#download
      - COLLECTION_DISPLAY_NAME=Europeana newspapers full-text
      - API_RETRIEVAL_THREAD_POOL_SIZE=10
      - FILE_PROCESSING_THREAD_POOL_SIZE=10
    volumes:
      - "${LOCAL_OUTPUT_DIR:-./output}:/output"
      - input-storage:/input
volumes:
  input-storage:
