version: "3.3"
services:
  fulltext-aggregator:
    image: fulltext-aggregator:latest
    build: ./image
    environment:
      - OUTPUT_DIR=/output
      - DO_CLEAN_UP=true
      - DEBUG=${DEBUG:-false}
      # - JDK_XML_ENTITY_EXPANSION_LIMIT=60000000
    volumes:
      - "${LOCAL_OUTPUT_DIR:-./output}:/output"
